############# English navigation ##############

# main menu
# [[main]]
# name = "Home"
# url = "/"
# weight = 1

# [[main]]
# name = "Sign Up"
# url = "/sign-up"
# weight = 2

# footer menu
[[footer]]
name = "Privacy Policy"
url = "/privacy-policy"
weight = 3
