############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Garden Map"
url = "/garden-map"
weight = 2

[[main]]
name = "Lineup"
url = "/lineup"
weight = 3

# footer menu
[[footer]]
name = "Privacy Policy"
url = "/privacy-policy"
weight = 3
